// Re-export UiSense composables for backward compatibility
export type {
  CannedGesture,
  ElementPosition,
  EyeOffset,
  EyeTrackingOptions,
  FaceLandmarkerBlendShapes,
  FaceLandmarkerResult,
  FaceLandmarkerState,
  GestureMapping,
  GestureRecognizerState,
  Handedness,
  HandLandmark,
  MousePosition,
  NoiseWatcher,
  PoseLandmarkerResult,
  PoseLandmarkerState,
  PrioritizationAction,
  RecognizedGesture,
  TrackingPosition,
  UseFaceLandmarkerOptions,
  UseGestureRecognizerOptions,
  UsePoseLandmarkerOptions,
  WizardState,
} from '@opentask/ui-sense';
export {
  createNoiseWatcher,
  useElementTracking,
  useEyeTracking,
  useFaceLandmarker,
  useGestureRecognizer,
  useGestureShortcuts,
  useMouseTracking,
  usePoseLandmarker,
} from '@opentask/ui-sense';
export * from './use-prioritization';
